# Generated by Django 4.2.7 on 2026-04-10 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('duree', models.PositiveSmallIntegerField(help_text='Durée en années')),
                ('description', models.TextField(blank=True)),
                ('debouches', models.TextField(blank=True, help_text='Débouchés séparés par des virgules')),
                ('domaine', models.CharField(choices=[('sciences', 'Sciences & Technologie'), ('sante', 'Santé & Médecine'), ('droit', 'Droit & Sciences Politiques'), ('economie', 'Économie & Gestion'), ('lettres', 'Lettres & Sciences Humaines'), ('agriculture', 'Agriculture & Environnement'), ('informatique', 'Informatique & Numérique'), ('education', "Sciences de l'Éducation"), ('art', 'Arts & Communication')], default='sciences', max_length=50)),
                ('exemples_metiers', models.TextField(blank=True, help_text='Exemples de métiers concrets')),
                ('salaire_moyen', models.CharField(blank=True, max_length=100)),
                ('taux_emploi', models.PositiveSmallIntegerField(blank=True, help_text="% d'emploi à 1 an", null=True)),
            ],
            options={
                'verbose_name': 'Filière',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Matière',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='SerieBac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Série de bac',
                'verbose_name_plural': 'Séries de bac',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Universite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('est_publique', models.BooleanField(default=True)),
                ('site_web', models.URLField(blank=True)),
                ('adresse', models.TextField(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('annee_creation', models.PositiveIntegerField(blank=True, null=True)),
                ('logo_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Université',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='UniversiteFiliere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField(default=2024)),
                ('seuil_minimum', models.FloatField(help_text='Note min pour admission (sur 20)')),
                ('seuil_demi_bourse', models.FloatField(help_text='Note min pour demi-bourse (sur 20)')),
                ('seuil_bourse', models.FloatField(help_text='Note min pour bourse complète (sur 20)')),
                ('places_disponibles', models.PositiveIntegerField(blank=True, null=True)),
                ('frais_inscription', models.PositiveIntegerField(blank=True, help_text='Frais en FCFA', null=True)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='univ_filieres', to='orienta.filiere')),
                ('universite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='univ_filieres', to='orienta.universite')),
            ],
            options={
                'verbose_name': 'Filière dans une université',
                'unique_together': {('universite', 'filiere', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='SerieMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.PositiveSmallIntegerField(default=1)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serie_matieres', to='orienta.matiere')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serie_matieres', to='orienta.seriebac')),
            ],
            options={
                'verbose_name': 'Matière par série',
                'unique_together': {('serie', 'matiere')},
            },
        ),
        migrations.CreateModel(
            name='FiliereSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filiere_series', to='orienta.filiere')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filiere_series', to='orienta.seriebac')),
            ],
            options={
                'verbose_name': 'Série acceptée par filière',
                'unique_together': {('filiere', 'serie')},
            },
        ),
        migrations.CreateModel(
            name='FiliereMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveSmallIntegerField(choices=[(1, 'Priorité 1'), (2, 'Priorité 2'), (3, 'Priorité 3')])),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filiere_matieres', to='orienta.filiere')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filiere_matieres', to='orienta.matiere')),
            ],
            options={
                'verbose_name': 'Matière prioritaire par filière',
                'ordering': ['ordre'],
                'unique_together': {('filiere', 'matiere')},
            },
        ),
    ]
